import {
  ROLE_BUILDER,
  ROLE_HARVESTER,
  ROLE_UPGRADER,
  ROLE_HAULER,
  ROLE_FILLER,
  ROLE_REPAIRER,
  ROLE_APOTHECARY,
} from "./config.roles";

export const BODY_PATTERNS: Record<string, BodyPartConstant[]> = {
  [ROLE_HAULER]: [CARRY, CARRY, MOVE],
  [ROLE_FILLER]: [CARRY, CARRY, MOVE],
  [ROLE_APOTHECARY]: [CARRY, CARRY, MOVE],
  [ROLE_BUILDER]: [WORK, WORK, CARRY, MOVE],
  [ROLE_REPAIRER]: [WORK, WORK, CARRY, MOVE],
  [ROLE_HARVESTER]: [WORK, CARRY, MOVE],
  [ROLE_UPGRADER]: [WORK, WORK, CARRY, MOVE],
};

export const MAX_BODY_PART_COUNT = 50;

export const SPAWN_ENERGY_RESERVE = 0.1;
